#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

require_output() {
  local output="$1"
  local expected="$2"

  if ! printf '%s\n' "$output" | grep -F "$expected" >/dev/null; then
    printf 'Missing expected diagnostics self-test output: %s\n' "$expected" >&2
    printf '%s\n' "$output" >&2
    exit 1
  fi
}

blocked_output="$(GARETH_DIAGNOSTICS_SELF_TEST=readiness-rollup "$ROOT/scripts/collect_runtime_diagnostics.sh")"
resource_discovery_output="$(GARETH_DIAGNOSTICS_SELF_TEST=resource-discovery "$ROOT/scripts/collect_runtime_diagnostics.sh")"
unknown_output="$(GARETH_DIAGNOSTICS_SELF_TEST=readiness-rollup-unknown "$ROOT/scripts/collect_runtime_diagnostics.sh")"
ready_output="$(GARETH_DIAGNOSTICS_SELF_TEST=readiness-rollup-ready "$ROOT/scripts/collect_runtime_diagnostics.sh")"
missing_bundles_output="$(GARETH_DIAGNOSTICS_SELF_TEST=missing-runtime-bundles "$ROOT/scripts/collect_runtime_diagnostics.sh")"
bundle_version_output="$(GARETH_DIAGNOSTICS_SELF_TEST=bundle-version-match "$ROOT/scripts/collect_runtime_diagnostics.sh")"
executable_readiness_output="$(GARETH_DIAGNOSTICS_SELF_TEST=executable-readiness "$ROOT/scripts/collect_runtime_diagnostics.sh")"
application_identity_output="$(GARETH_DIAGNOSTICS_SELF_TEST=application-identity "$ROOT/scripts/collect_runtime_diagnostics.sh")"
team_id_output="$(GARETH_DIAGNOSTICS_SELF_TEST=team-id "$ROOT/scripts/collect_runtime_diagnostics.sh")"
extension_host_entitlement_output="$(GARETH_DIAGNOSTICS_SELF_TEST=extension-host-entitlement "$ROOT/scripts/collect_runtime_diagnostics.sh")"
mach_service_output="$(GARETH_DIAGNOSTICS_SELF_TEST=mach-service "$ROOT/scripts/collect_runtime_diagnostics.sh")"
application_group_output="$(GARETH_DIAGNOSTICS_SELF_TEST=application-group "$ROOT/scripts/collect_runtime_diagnostics.sh")"
camera_device_output="$(GARETH_DIAGNOSTICS_SELF_TEST=camera-device "$ROOT/scripts/collect_runtime_diagnostics.sh")"
video_metadata_output="$(GARETH_DIAGNOSTICS_SELF_TEST=video-metadata "$ROOT/scripts/collect_runtime_diagnostics.sh")"
file_byte_count_output="$(GARETH_DIAGNOSTICS_SELF_TEST=file-byte-count "$ROOT/scripts/collect_runtime_diagnostics.sh")"
video_parser_output="$(GARETH_DIAGNOSTICS_SELF_TEST=video-parser GARETH_DIAGNOSTICS_VIDEO_FIXTURE="$ROOT/Extension/video.mp4" "$ROOT/scripts/collect_runtime_diagnostics.sh")"
stub_parser_dir="$TMP_DIR/stub-parser/scripts"
mkdir -p "$stub_parser_dir"
cp "$ROOT/scripts/collect_runtime_diagnostics.sh" "$stub_parser_dir/collect_runtime_diagnostics.sh"
chmod +x "$stub_parser_dir/collect_runtime_diagnostics.sh"
cat >"$stub_parser_dir/validate_project.py" <<'PY'
def mp4_video_metadata(path):
    return {"dimensions": (1280, 720), "frame_rate": 24, "duration_seconds": 0}
PY
zero_duration_video_fixture="$TMP_DIR/zero-duration.mp4"
: >"$zero_duration_video_fixture"
zero_duration_video_parser_output="$(GARETH_DIAGNOSTICS_SELF_TEST=video-parser GARETH_DIAGNOSTICS_VIDEO_FIXTURE="$zero_duration_video_fixture" "$stub_parser_dir/collect_runtime_diagnostics.sh")"
registration_output="$(GARETH_DIAGNOSTICS_SELF_TEST=registration "$ROOT/scripts/collect_runtime_diagnostics.sh")"
activation_evidence_output="$(GARETH_DIAGNOSTICS_SELF_TEST=activation-evidence "$ROOT/scripts/collect_runtime_diagnostics.sh")"

require_output "$blocked_output" "Ready fixture: yes"
require_output "$blocked_output" "Blocked fixture: no"
require_output "$blocked_output" "Unknown fixture: unknown"
require_output "$blocked_output" "Runtime readiness result: blocked"
require_output "$blocked_output" "Runtime readiness checks ready: 1/3"
require_output "$blocked_output" "Runtime readiness checks blocked: 1"
require_output "$blocked_output" "Runtime readiness checks unknown: 1"
require_output "$blocked_output" "Runtime readiness next action: resolve Blocked fixture"

require_output "$resource_discovery_output" "Diagnostics script path:"
require_output "$resource_discovery_output" "Diagnostics script directory:"
require_output "$resource_discovery_output" "Diagnostics parser path:"
require_output "$resource_discovery_output" "Diagnostics parser source: adjacent script resource"
require_output "$resource_discovery_output" "Diagnostics parser available: yes"

require_output "$unknown_output" "Ready fixture: yes"
require_output "$unknown_output" "Unknown fixture: unknown"
require_output "$unknown_output" "Runtime readiness result: incomplete"
require_output "$unknown_output" "Runtime readiness checks ready: 1/2"
require_output "$unknown_output" "Runtime readiness checks blocked: 0"
require_output "$unknown_output" "Runtime readiness checks unknown: 1"
require_output "$unknown_output" "Runtime readiness next action: inspect Unknown fixture"

require_output "$ready_output" "Ready fixture: yes"
require_output "$ready_output" "Runtime readiness result: ready"
require_output "$ready_output" "Runtime readiness checks ready: 1/1"
require_output "$ready_output" "Runtime readiness checks blocked: 0"
require_output "$ready_output" "Runtime readiness checks unknown: 0"
require_output "$ready_output" "Runtime readiness next action: submit the system extension request"

require_output "$missing_bundles_output" "Application location ready: no"
require_output "$missing_bundles_output" "App bundle identifier ready: no"
require_output "$missing_bundles_output" "App signature ready: no"
require_output "$missing_bundles_output" "App System Extension entitlement ready: no"
require_output "$missing_bundles_output" "App executable ready: no"
require_output "$missing_bundles_output" "Extension bundle identifier ready: no"
require_output "$missing_bundles_output" "Extension signature ready: no"
require_output "$missing_bundles_output" "Extension host-only entitlement absent: no"
require_output "$missing_bundles_output" "Extension executable ready: no"
require_output "$missing_bundles_output" "Extension CMIO Mach service ready: no"
require_output "$missing_bundles_output" "Bundle versions match ready: no"
require_output "$missing_bundles_output" "Signing Team match ready: no"
require_output "$missing_bundles_output" "Application group match ready: no"
require_output "$missing_bundles_output" "Bundled video ready: no"
require_output "$missing_bundles_output" "Bundled video metadata ready: no"
require_output "$missing_bundles_output" "Runtime readiness result: blocked"
require_output "$missing_bundles_output" "Runtime readiness checks ready: 0/15"
require_output "$missing_bundles_output" "Runtime readiness checks blocked: 15"
require_output "$missing_bundles_output" "Runtime readiness checks unknown: 0"
require_output "$missing_bundles_output" "Runtime readiness next action: resolve Application location ready"

require_output "$bundle_version_output" "Bundle version match fixture: yes"
require_output "$bundle_version_output" "Bundle version short mismatch fixture: no"
require_output "$bundle_version_output" "Bundle version build mismatch fixture: no"
require_output "$bundle_version_output" "Bundle version missing fixture: no"

require_output "$executable_readiness_output" "Executable missing name fixture: no"
require_output "$executable_readiness_output" "Executable missing file fixture: no"
require_output "$executable_readiness_output" "Executable non-executable fixture: no"
require_output "$executable_readiness_output" "Executable ready fixture: yes"
require_output "$executable_readiness_output" "Executable path-like name fixture: no"

require_output "$application_identity_output" "App path match fixture: yes"
require_output "$application_identity_output" "App path mismatch fixture: no"
require_output "$application_identity_output" "Application location existing fixture: yes"
require_output "$application_identity_output" "Application location missing fixture: no"
require_output "$application_identity_output" "Application location mismatch fixture: no"
require_output "$application_identity_output" "Bundle identifier match fixture: yes"
require_output "$application_identity_output" "Bundle identifier mismatch fixture: no"
require_output "$application_identity_output" "Bundle identifier missing fixture: no"
require_output "$application_identity_output" "Info.plist string metadata fixture: com.example.StringMetadata"
require_output "$application_identity_output" "Info.plist scalar metadata fixture: missing"
require_output "$application_identity_output" "Info.plist blank string metadata fixture: missing"
require_output "$application_identity_output" "Info.plist untrimmed string metadata fixture: missing"
require_output "$application_identity_output" "Info.plist nested string metadata fixture: com.example.StringMetadata.Extension"
require_output "$application_identity_output" "Info.plist nested scalar metadata fixture: missing"
require_output "$application_identity_output" "Info.plist nested blank string metadata fixture: missing"
require_output "$application_identity_output" "Info.plist nested untrimmed string metadata fixture: missing"

require_output "$team_id_output" "Team ID match fixture: yes"
require_output "$team_id_output" "Team ID mismatch fixture: no"
require_output "$team_id_output" "Team ID missing app fixture: no"
require_output "$team_id_output" "Team ID missing extension fixture: no"
require_output "$team_id_output" "Team ID short fixture: no"
require_output "$team_id_output" "Team ID dotted fixture: no"
require_output "$team_id_output" "Team ID multiple app fixture: no"
require_output "$team_id_output" "Team ID multiple extension fixture: no"

require_output "$extension_host_entitlement_output" "Boolean entitlement all architectures present fixture: yes"
require_output "$extension_host_entitlement_output" "Boolean entitlement missing architecture fixture: no"
require_output "$extension_host_entitlement_output" "Boolean entitlement unreadable architecture fixture: unknown"
require_output "$extension_host_entitlement_output" "Boolean entitlement empty architecture fixture: unknown"
require_output "$extension_host_entitlement_output" "Boolean entitlement malformed plist fixture: unknown"
require_output "$extension_host_entitlement_output" "Boolean entitlement scalar fixture: unknown"
require_output "$extension_host_entitlement_output" "Boolean entitlement fallback scalar fixture: unknown"
require_output "$extension_host_entitlement_output" "Extension host entitlement valid absent fixture: yes"
require_output "$extension_host_entitlement_output" "Extension host entitlement valid present fixture: no"
require_output "$extension_host_entitlement_output" "Extension host entitlement invalid signature fixture: no"
require_output "$extension_host_entitlement_output" "Extension host entitlement unreadable fixture: no"

require_output "$mach_service_output" "Mach service direct fixture resolved: yes"
require_output "$mach_service_output" "Mach service direct fixture matches expected: yes"
require_output "$mach_service_output" "Mach service direct fixture ready: yes"
require_output "$mach_service_output" "Mach service team-prefixed fixture ready: yes"
require_output "$mach_service_output" "Mach service short-prefix fixture ready: no"
require_output "$mach_service_output" "Mach service dotted-prefix fixture ready: no"
require_output "$mach_service_output" "Mach service unresolved fixture resolved: no"
require_output "$mach_service_output" "Mach service wrong fixture matches expected: no"
require_output "$mach_service_output" "Mach service missing fixture ready: no"

require_output "$application_group_output" "Application group direct fixture ready: no"
require_output "$application_group_output" "Application group shared fixture ready: yes"
require_output "$application_group_output" "Application group missing fixture ready: no"
require_output "$application_group_output" "Application group mismatched fixture ready: no"
require_output "$application_group_output" "Application group short-prefix fixture ready: no"
require_output "$application_group_output" "Application group wrong suffix fixture ready: no"
require_output "$application_group_output" "Application group dotted-prefix fixture ready: no"
require_output "$application_group_output" "Application group unresolved fixture ready: no"
require_output "$application_group_output" "Application group empty format fixture: none"
require_output "$application_group_output" "Application group list format fixture: ABCDE12345.com.garethpaul.GarethVideoCam, ZYXWV98765.com.garethpaul.GarethVideoCam"
require_output "$application_group_output" "Application group all architectures common fixture: ABCDE12345.com.garethpaul.GarethVideoCam"
require_output "$application_group_output" "Application group missing architecture common fixture: none"
require_output "$application_group_output" "Application group malformed entitlements readable fixture: no"
require_output "$application_group_output" "Application group scalar entitlements readable fixture: no"
require_output "$application_group_output" "Application group non-string entitlements readable fixture: no"
require_output "$application_group_output" "Application group untrimmed entitlements readable fixture: no"
require_output "$application_group_output" "Application group fallback scalar entitlements readable fixture: no"
require_output "$application_group_output" "Application group fallback non-string entitlements readable fixture: no"
require_output "$application_group_output" "Application group fallback untrimmed entitlements readable fixture: no"
require_output "$application_group_output" "Application group fallback malformed entitlements readable fixture: no"

require_output "$camera_device_output" "Camera device present fixture: yes"
require_output "$camera_device_output" "Camera device missing fixture: no"
require_output "$camera_device_output" "Camera device substring fixture: no"
require_output "$camera_device_output" "Camera device empty fixture: unknown"

require_output "$video_metadata_output" "Video metadata parsed width fixture: 1280"
require_output "$video_metadata_output" "Video metadata parsed height fixture: 720"
require_output "$video_metadata_output" "Video metadata parsed duration fixture: 12.5"
require_output "$video_metadata_output" "Video metadata spaced width fixture: 1280"
require_output "$video_metadata_output" "Video metadata quoted duration fixture: 12.5"
require_output "$video_metadata_output" "Video metadata preferred parser fixture: 1280"
require_output "$video_metadata_output" "Video metadata blank fallback fixture: 640"
require_output "$video_metadata_output" "Video metadata null fallback fixture: 640"
require_output "$video_metadata_output" "Video metadata parenthesized null fallback fixture: 640"
require_output "$video_metadata_output" "Video metadata ready fixture: yes"
require_output "$video_metadata_output" "Video metadata decimal fixture: yes"
require_output "$video_metadata_output" "Video metadata non-numeric width fixture: no"
require_output "$video_metadata_output" "Video metadata wrong width fixture: no"
require_output "$video_metadata_output" "Video metadata wrong frame rate fixture: no"
require_output "$video_metadata_output" "Video metadata missing frame rate fixture: unknown"
require_output "$video_metadata_output" "Video metadata missing duration fixture: unknown"
require_output "$video_metadata_output" "Video metadata zero duration fixture: no"
require_output "$video_metadata_output" "Video metadata negative duration fixture: no"

require_output "$file_byte_count_output" "File byte count fixture: 5"
require_output "$file_byte_count_output" "Video SHA-256: unknown"

require_output "$video_parser_output" "Video parser pixel width fixture: 1280"
require_output "$video_parser_output" "Video parser pixel height fixture: 720"
require_output "$video_parser_output" "Video parser frame rate fixture: 24"
require_output "$video_parser_output" "Video parser duration fixture: 3.0833333333333335"
require_output "$video_parser_output" "Video parser metadata ready fixture: yes"
require_output "$zero_duration_video_parser_output" "MP4 parser duration seconds = 0"
require_output "$zero_duration_video_parser_output" "Video parser duration fixture: 0"
require_output "$zero_duration_video_parser_output" "Video parser metadata ready fixture: no"

require_output "$registration_output" "Registration active fixture present: yes"
require_output "$registration_output" "Registration active fixture activated enabled: yes"
require_output "$registration_output" "Registration reversed fixture activated enabled: yes"
require_output "$registration_output" "Registration waiting fixture activated enabled: no"
require_output "$registration_output" "Registration deactivated fixture activated enabled: no"
require_output "$registration_output" "Registration longer identifier fixture present: no"
require_output "$registration_output" "Registration longer identifier fixture activated enabled: no"
require_output "$registration_output" "Registration missing fixture present: no"
require_output "$registration_output" "Registration empty fixture present: unknown"

require_output "$activation_evidence_output" "Runtime activation evidence result: active"
require_output "$activation_evidence_output" "Runtime activation evidence checks ready: 3/3"
require_output "$activation_evidence_output" "Runtime activation evidence next action: open a camera picker and confirm Gareth Video Cam is selectable"
require_output "$activation_evidence_output" "Runtime activation evidence result: blocked"
require_output "$activation_evidence_output" "Runtime activation evidence next action: resolve Extension registration entry present"
require_output "$activation_evidence_output" "Runtime activation evidence result: incomplete"
require_output "$activation_evidence_output" "Runtime activation evidence next action: inspect Extension registration activated enabled"
require_output "$activation_evidence_output" "Runtime activation evidence checks ready: 0/3"
require_output "$activation_evidence_output" "Runtime activation evidence checks unknown: 3"
require_output "$activation_evidence_output" "Runtime activation evidence next action: inspect Extension registration entry present"

printf 'Runtime diagnostics tests passed.\n'
